-- mode ------ key --------------- command --------------------------------- opts
Utils.Shared.addGlobalKeybinds({
-- save & qui, t
  { 'n'      ,'<c-s>'             ,'<esc>:w<cr>'                            ,'ns' },
  { 'v'      ,'<c-s>'             ,'<esc>:w<cr>'                            ,'ns' },
  { 'c'      ,'<c-s>'             ,'<esc>:w<cr>'                            ,'ns' },
  { 'i'      ,'<c-s>'             ,'<esc>:w<cr>'                            ,'ns' },
  { 'n'      ,'Q'                 ,'<esc>:q!<cr>'                           ,'ns' },
  { 'n'      ,'<c-q>'             ,'<esc>:q<cr>'                            ,'ns' },
  { 'v'      ,'<c-q>'             ,'<esc>:q<cr>'                            ,'ns' },
  { 'i'      ,'<c-q>'             ,'<esc>:q<cr>'                            ,'ns' },
  { 'n'      ,'tee'               ,':w !sudo tee %<cr>'                     ,'ns' },
-- 分屏,调整, 分屏大小
  { 'n'      ,'sk'                ,':set nosplitbelow<cr>:split<cr>'        ,'ns' },
  { 'n'      ,'sj'                ,':set splitright<cr>:split<cr>'          ,'ns' },
  { 'n'      ,'sh'                ,':set nosplitright<cr>:vsplit<cr>'       ,'ns' },
  { 'n'      ,'sl'                ,':set splitright<cr>:vsplit<cr>'         ,'ns' },
  { 'n'      ,'<c-h>'             ,'<c-w>h'                                 ,'ns' },
  { 'n'      ,'<c-l>'             ,'<c-w>l'                                 ,'ns' },
  { 'n'      ,'<c-up>'            ,':res +2<cr>'                            ,'ns' },
  { 'n'      ,'<c-down>'          ,':res -2<cr>'                            ,'ns' },
  { 'n'      ,'<c-left>'          ,':vertical resize+2<cr>'                 ,'ns' },
  { 'n'      ,'<c-right>'         ,':vertical resize-2<cr>'                 ,'ns' },
-- editor
  { 'n'      ,'<c-j>'             ,'10gj'                                   ,'ns' },
  { 'n'      ,'<c-k>'             ,'10gk'                                   ,'ns' },
  { 'v'      ,'<c-j>'             ,'10gj'                                   ,'ns' },
  { 'v'      ,'<c-k>'             ,'10gk'                                   ,'ns' },
  { 'i'      ,'<c-j>'             ,'<esc>'                                  ,'ns' },
  { 'i'      ,'<c-k>'             ,'<esc>'                                  ,'ns' },
  { 'n'      ,'<leader><cr>'      ,':nohlsearch<cr>'                        ,'ns' },
  { 'v'      ,'<leader><cr>'      ,':nohlsearch<cr>'                        ,'ns' },
  { 'v'      ,'p'                 ,'"8dP"'                                  ,'ns' },
  { 'i'      ,'<c-p>'             ,'<c-r>"'                                 ,'ns' },
  { 'n'      ,'<leader>rw'        ,'ea<c-w><c-r>+<esc>:w<cr>'               ,'ns' },
  { 'n'      ,'<leader>r`'        ,'"8di`P:w<cr>'                           ,'ns' },
  { 'n'      ,'<leader>r\''       ,'"8di\'P:w<cr>'                          ,'ns' },
  { 'n'      ,'<leader>r"'        ,'"8di"P:w<cr>'                           ,'ns' },
  { 'n'      ,'<leader>r)'        ,'"8di)P:w<cr>'                           ,'ns' },
  { 'n'      ,'<leader>r]'        ,'"8di]P:w<cr>'                           ,'ns' },
  { 'n'      ,'<leader>r}'        ,'"8di}P:w<cr>'                           ,'ns' },
  { 'n'      ,'<leader>rt'        ,'"8ditP:w<cr>'                           ,'ns' },
  { 'n'      ,'<leader>h'         ,'yiw:h <c-r>"<cr>'                       ,'ns' },
  { 'n'      ,'<leader><leader>'  ,'/<++><cr>"8d4l:nohlsearch<cr>i'         ,'ns' },
  { 'n'      ,'<leader>n'         ,'<esc>a<++><esc>'                        ,'ns' },
-- fast move
  { 'n'      ,'H'                 ,'g^'                                     ,'ns' },
  { 'n'      ,'L'                 ,'g_'                                     ,'ns' },
  { 'v'      ,'H'                 ,'g^'                                     ,'ns' },
  { 'v'      ,'L'                 ,'g_'                                     ,'ns' },
  { 'n'      ,'<'                 ,'<<'                                     ,'ns' },
  { 'n'      ,'>'                 ,'>>'                                     ,'ns' },
  { 'x'      ,'<'                 ,'<gv'                                    ,'ns' },
  { 'x'      ,'>'                 ,'>gv'                                    ,'ns' },
})
